# Generated by Django 5.2.15 on 2026-06-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Me', max_length=100)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
