# Generated by Django 5.2.15 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
