# Generated by Django 5.2.15 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_artwork_medium_artwork_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
